default: &default
  geocoding_api_key: <%= ENV['GEOCODING_API_KEY'] %>
  elasticsearch_url: <%= ENV['ELASTICSEARCH_URL'] %>

development:
  <<: *default
  secret_key_base: dde29a5ca1a2f51ba4edf02ff2008178b23723a6e9e56b50fa49cfa570c3a79b3ece58cde0b819580a3faa3171b61e8b269161c4cda7b84bc72512fcebdf8fb7

test:
  <<: *default
  secret_key_base: 695827349d7793d023dd6aeb05e2b0b2db6c6f9a8552cbf2116910e6688cd9afde161eb8728afe57049bd85af84f82dd33a7f485e3733fdc30623200e7c92d6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
